/* KDE Color Scheme - generated from palette (works for ALL KDE apps, Qt5 + Qt6) */
[ColorEffects:Disabled]
ColorAmount=0
ColorEffectAmount=0
ContrastAmount=0.65
ContrastEffectAmount=0
IntensityAmount=0
IntensityEffectAmount=0

[ColorEffects:Inactive]
ChangeSelectionColor=true
ColorAmount=0.025
ColorEffectAmount=0.4
ContrastAmount=0.1
ContrastEffectAmount=0.4
Enable=false
IntensityAmount=0
IntensityEffectAmount=0.4

[Colors:Button]
BackgroundAlternate={{dark_background}}
BackgroundNormal={{lighter_background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[Colors:Complementary]
BackgroundAlternate={{darker_background}}
BackgroundNormal={{dark_background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[Colors:Header]
BackgroundAlternate={{dark_background}}
BackgroundNormal={{background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[Colors:Selection]
BackgroundAlternate={{blue}}
BackgroundNormal={{blue}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{background}}
ForegroundDisabled={{muted}}
ForegroundInactive={{background}}
ForegroundLink={{background}}
ForegroundNegative={{background}}
ForegroundNeutral={{background}}
ForegroundNormal={{background}}
ForegroundVisited={{background}}

[Colors:Tooltip]
BackgroundAlternate={{dark_background}}
BackgroundNormal={{lighter_background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[Colors:View]
BackgroundAlternate={{dark_background}}
BackgroundNormal={{background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[Colors:Window]
BackgroundAlternate={{dark_background}}
BackgroundNormal={{background}}
DecorationFocus={{accent}}
DecorationHover={{accent}}
ForegroundActive={{blue}}
ForegroundDisabled={{dark_foreground}}
ForegroundInactive={{dark_foreground}}
ForegroundLink={{blue}}
ForegroundNegative={{red}}
ForegroundNeutral={{cyan}}
ForegroundNormal={{foreground}}
ForegroundVisited={{magenta}}

[General]
ColorScheme=Palette
Name=Palette
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={{background}}
activeBlend={{background}}
activeForeground={{foreground}}
inactiveBackground={{dark_background}}
inactiveBlend={{dark_background}}
inactiveForeground={{dark_foreground}}
