{
  "$schema": "https://opencode.ai/theme.json",
  "theme": {
    "primary": "{{ accent }}",
    "secondary": "{{ bright_blue }}",
    "accent": "{{ bright_foreground }}",
    "error": "{{ red }}",
    "warning": "{{ orange }}",
    "success": "{{ green }}",
    "info": "{{ cyan }}",
    "text": "{{ foreground }}",
    "textMuted": "{{ muted }}",
    "selectedListItemText": "{{ background }}",
    "background": "{{ background }}",
    "backgroundPanel": "{{ dark_background }}",
    "backgroundElement": "{{ darker_background }}",
    "border": "{{ lighter_background }}",
    "borderActive": "{{ accent }}",
    "borderSubtle": "{{ darker_background }}",
    "diffAdded": "{{ green }}",
    "diffRemoved": "{{ red }}",
    "diffContext": "{{ muted }}",
    "diffHunkHeader": "{{ bright_blue }}",
    "diffHighlightAdded": "{{ bright_green }}",
    "diffHighlightRemoved": "{{ bright_red }}",
    "diffAddedBg": "{{ selection }}",
    "diffRemovedBg": "{{ selection }}",
    "diffContextBg": "{{ darker_background }}",
    "diffLineNumber": "{{ muted }}",
    "diffAddedLineNumberBg": "{{ selection }}",
    "diffRemovedLineNumberBg": "{{ selection }}",
    "markdownText": "{{ foreground }}",
    "markdownHeading": "{{ bright_foreground }}",
    "markdownLink": "{{ accent }}",
    "markdownLinkText": "{{ cyan }}",
    "markdownCode": "{{ green }}",
    "markdownBlockQuote": "{{ muted }}",
    "markdownEmph": "{{ dark_foreground }}",
    "markdownStrong": "{{ bright_foreground }}",
    "markdownHorizontalRule": "{{ muted }}",
    "markdownListItem": "{{ accent }}",
    "markdownListEnumeration": "{{ cyan }}",
    "markdownImage": "{{ yellow }}",
    "markdownImageText": "{{ cyan }}",
    "markdownCodeBlock": "{{ dark_foreground }}",
    "syntaxComment": "{{ muted }}",
    "syntaxKeyword": "{{ magenta }}",
    "syntaxFunction": "{{ bright_cyan }}",
    "syntaxVariable": "{{ yellow }}",
    "syntaxString": "{{ green }}",
    "syntaxNumber": "{{ orange }}",
    "syntaxType": "{{ bright_blue }}",
    "syntaxOperator": "{{ magenta }}",
    "syntaxPunctuation": "{{ foreground }}"
  }
}