# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#eff1f5"

# Main text color
theme[main_fg]="#4c4f69"

# Title color for boxes
theme[title]="#4c4f69"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#1e66f5"

# Background color of selected item in processes box
theme[selected_bg]="#ccd0da"

# Foreground color of selected item in processes box
theme[selected_fg]="#1e66f5"

# Color of inactive/disabled text
theme[inactive_fg]="#acb0be"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#5c5f77"

# Background color of the percentage meters
theme[meter_bg]="#ccd0da"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#5c5f77"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#ea76cb"
theme[mem_box]="#40a02b"
theme[net_box]="#d20f39"
theme[proc_box]="#1e66f5"

# Box divider line and small boxes line color
theme[div_line]="#acb0be"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#40a02b"
theme[temp_mid]="#df8e1d"
theme[temp_end]="#d20f39"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#179299"
theme[cpu_mid]="#1e66f5"
theme[cpu_end]="#ea76cb"

# Mem/Disk free meter
theme[free_start]="#ea76cb"
theme[free_mid]="#1e66f5"
theme[free_end]="#179299"

# Mem/Disk cached meter
theme[cached_start]="#1e66f5"
theme[cached_mid]="#179299"
theme[cached_end]="#ea76cb"

# Mem/Disk available meter
theme[available_start]="#df8e1d"
theme[available_mid]="#d20f39"
theme[available_end]="#d20f39"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#40a02b"
theme[used_mid]="#179299"
theme[used_end]="#1e66f5"

# Download graph colors
theme[download_start]="#df8e1d"
theme[download_mid]="#d20f39"
theme[download_end]="#d20f39"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#40a02b"
theme[upload_mid]="#179299"
theme[upload_end]="#1e66f5"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#179299"
theme[process_mid]="#1e66f5"
theme[process_end]="#ea76cb"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#eff1f5"
theme[gradient_color_1]="#dce0e8"
theme[gradient_color_2]="#ccd0da"
theme[gradient_color_3]="#acb0be"
theme[gradient_color_4]="#9ca0b0"
theme[gradient_color_5]="#4c4f69"
theme[gradient_color_6]="#5c5f77"
theme[gradient_color_7]="#4c4f69"
