# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1a1111"

# Main text color
theme[main_fg]="#f1dedd"

# Title color for boxes
theme[title]="#f1dedd"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffb3ae"

# Background color of selected item in processes box
theme[selected_bg]="#322827"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffb3ae"

# Color of inactive/disabled text
theme[inactive_fg]="#a08c8a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#534342"

# Background color of the percentage meters
theme[meter_bg]="#322827"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#534342"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#904a46"
theme[mem_box]="#e7bdb9"
theme[net_box]="#ffb4ab"
theme[proc_box]="#ffb3ae"

# Box divider line and small boxes line color
theme[div_line]="#a08c8a"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#e7bdb9"
theme[temp_mid]="#e2c28c"
theme[temp_end]="#ffb4ab"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#ffdad7"
theme[cpu_mid]="#ffb3ae"
theme[cpu_end]="#904a46"

# Mem/Disk free meter
theme[free_start]="#904a46"
theme[free_mid]="#ffb3ae"
theme[free_end]="#ffdad7"

# Mem/Disk cached meter
theme[cached_start]="#ffb3ae"
theme[cached_mid]="#ffdad7"
theme[cached_end]="#904a46"

# Mem/Disk available meter
theme[available_start]="#e2c28c"
theme[available_mid]="#ffb4ab"
theme[available_end]="#ffb4ab"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#e7bdb9"
theme[used_mid]="#ffdad7"
theme[used_end]="#ffb3ae"

# Download graph colors
theme[download_start]="#e2c28c"
theme[download_mid]="#ffb4ab"
theme[download_end]="#ffb4ab"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#e7bdb9"
theme[upload_mid]="#ffdad7"
theme[upload_end]="#ffb3ae"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#ffdad7"
theme[process_mid]="#ffb3ae"
theme[process_end]="#904a46"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#1a1111"
theme[gradient_color_1]="#3d3231"
theme[gradient_color_2]="#322827"
theme[gradient_color_3]="#a08c8a"
theme[gradient_color_4]="#d8c2bf"
theme[gradient_color_5]="#f1dedd"
theme[gradient_color_6]="#534342"
theme[gradient_color_7]="#733330"
