
# ~/.config/hypr/hyprlock.conf
source = ~/.config/current_theme/hyprlock.conf

animation = fadeIn, 0, 0, default
animation = fadeOut, 0, 0, default
general {
    hide_cursor = false
    immediate-render = true
}


background {
    monitor =
    path =  ~/.config/current_theme/current_wallpaper.png #screenshot
    #immediate_render = true
    blur_passes = 3
    blur_size = 7

    #noise = 0.015
    contrast = 1.15
    brightness = 0.75
    #vibrancy = 0.20
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"

    color = $font_color

    font_size = 80
    font_family = CaskaydiaMono
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B %Y')"

    color = $font_color

    font_size = 24
    font_family = CaskaydiaMono

    position = 0, 90
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000000] echo "" "$USER" @ "$HOSTNAME"

    color = $check_color

    font_size = 22
    font_family = CaskaydiaMono

    position = 0, -50
    halign = center
    valign = center
}


input-field {
    monitor =

    size = 450, 70

    outline_thickness = 2
    rounding = 0 #35

    outer_color = $outer_color
    inner_color = $inner_color

    font_color = $font_color

    check_color = $check_color
    fail_color = $font_color

    fail_text = Wrong Password

    dots_center = true
    dots_size = 0.22
    dots_spacing = 0.30

    fade_on_empty = false

    placeholder_text = Enter Password
    #placeholder_text_color = rgba(ffffff88)

    position = 0, -140
    halign = center
    valign = center

    ignore_empty_input = true
}


# Bottom hint or other text
label {
    monitor =
    text =  Work to "BECOME", not to ACQUIRE  #cmd[update:1000000] curl -sL --fail https://dummyjson.com/quotes/random | jq -r ' "[ \(.quote) ]\n— \(.author)"'

    color = $check_color

    font_size = 14
    font_family = CaskaydiaMono
    position = 0, -510
    halign = center
    valign = center
}

