-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

--hl.config({ autogenerated = true }) -- remove this line to remove the warning
-- hl.config({
-- 	debug = {
-- 		suppress_errors = true,
-- 	},
-- })

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")
------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
--local fileManager = "nautilus"
local menu = "walker"
local browser = "chromium" --"firefox"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
	hl.exec_cmd("waybar & swaybg -i ~/.config/current_theme/current_wallpaper.png &")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("systemctl --user start elephant.service")
	hl.exec_cmd("walker --gapplication-service &")
	hl.exec_cmd("$HOME/.local/bin/keyboard")
	hl.exec_cmd("mpd-mpris &")
	--hl.exec_cmd("waybar & hyprpaper & firefox")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("SAL_USE_VCLPLUGIN", "gtk3")

--hl.env("GDK_BACKEND", "wayland, x11")
--hl.env("GTK_THEME", "Adwaita")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 1,
		gaps_out = 2,

		border_size = 1,

		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		--rounding = 10,

		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0, --0.9,
		inactive_opacity = 1.0, --0.8,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 3,
			passes = 4,
			brightness = 3,
			contrast = 3,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 1, bezier = "quick" })
hl.animation({ leaf = "border", enabled = true, speed = 0.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 0.79, bezier = "quick" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 0.1, bezier = "quick", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 0.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 0.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 0.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 0.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 0.81, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 0.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = false, speed = 0.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = false, speed = 0.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 0.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = false, speed = 0.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = false, speed = 0.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 1, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
hl.window_rule({
	name = "tui-float-overlay",
	match = { class = "tui-float" },
	float = true,
	size = { 940, 650 },
	center = true,
	--stay_focused = true,
	--rounding     = 8,
})

hl.window_rule({
	name = "about-tui-float-overlay",
	match = { class = "about-tui-float" },
	float = true,
	size = { 940, 540 },
	center = true,
	--stay_focused = true,
	--rounding     = 8,
})

hl.window_rule({
	name = "floating-apps",
	match = { class = "^(org.localsend.localsend_app|imv|mpv)$" },
	--to add other classes use pipe | right before ")", remember no spaces with pipe
	float = true,
	size = { 950, 650 },
	center = true,
})

hl.window_rule({
	name = "pip-float",
	match = { class = "firefox", title = "Picture-in-Picture" },
	float = true,
	size = { 950, 650 },
	center = true,
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		numlock_by_default = true,

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(
	mainMod .. " + ALT + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

--walker & menus
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + CTRL + E", hl.dsp.exec_cmd("walker -m symbols"))
hl.bind(mainMod .. " + CTRL + C", hl.dsp.exec_cmd("walker -m clipboard"))

hl.bind(
	mainMod .. " + CTRL + K",
	hl.dsp.exec_cmd("cat ~/.config/hypr/extras/hl_binds.txt | walker --dmenu -p ' Search Keybinds...' --width 800")
)

--theme change
hl.bind(
	mainMod .. " + CTRL + SHIFT + SPACE ",
	hl.dsp.exec_cmd('walker -p " Search themes..." -m "menus:theme_switcher"')
)
--wallpaper change
hl.bind(
	mainMod .. " + CTRL + SPACE",
	hl.dsp.exec_cmd('walker -p " Search wallpapers..." -m "menus:wallpaper_switcher"')
)
--theme-change based on wallpaper
hl.bind(
	mainMod .. " + SHIFT + SPACE",
	hl.dsp.exec_cmd('walker -p " Search wallpapers for custom theme..." -m "menus:wallpaper_theme_switcher"')
)
--toggle night mode
hl.bind(mainMod .. "+ CTRL + N", hl.dsp.exec_cmd("~/.local/bin/night-mode"))

-- some webapps
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("chromium --app=https://youtube.com"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("chromium --app=https://mail.google.com/mail/u/1/"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("chromium --app=https://cinejoy.to"))

-- some other apps
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("localsend"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("obsidian"))

-- toggle focus strictly between float window and tiled window
hl.bind(mainMod .. " + TAB", function()
	local win = hl.get_active_window()
	if not win then
		return
	end

	if win.floating then
		hl.dispatch(hl.dsp.focus({ window = "tiled" }))
	else
		hl.dispatch(hl.dsp.focus({ window = "floating" }))
	end
end)

--floating tuis
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd("~/.local/bin/launch-focus-tui impala"))
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd("~/.local/bin/launch-focus-tui bluetui"))
hl.bind(mainMod .. " + CTRL + T", hl.dsp.exec_cmd("~/.local/bin/launch-focus-tui btop"))
hl.bind(mainMod .. " + CTRL + A", hl.dsp.exec_cmd("~/.local/bin/launch-focus-tui wiremix"))

hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("~/.local/bin/launch-focus-tui rmpc"))
--powermenu
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("~/.local/bin/powermenu"))

--printscreen
hl.bind(
	"Print",
	hl.dsp.exec_cmd(
		'GEOM=$(slurp) && [ -n "$GEOM" ] && TMP_IMG="/tmp/screenshot_preview.png" && grim -g "$GEOM" - | tee "$TMP_IMG" | wl-copy && notify-send -t 2000 -i "$TMP_IMG" "󰂚 Image Copied" "Copied to Clipboard" && rm "$TMP_IMG"'
	)
)

hl.bind(
	"SHIFT + Print",
	hl.dsp.exec_cmd(
		'GEOM=$(slurp) && [ -n "$GEOM" ] && FILE="$HOME/Pictures/screenshots/screenshot_$(date +%Y-%m-%d_%H-%M-%S).png" && grim -g "$GEOM" "$FILE" && sleep 0.1 && notify-send -t 2000 -i "$FILE" "󰂚 Image Saved" "Saved to ~/Pictures/screenshots"'
	)
)

hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("~/.local/bin/color-picker"))
hl.bind(mainMod .. " + ALT + PRINT", hl.dsp.exec_cmd("~/.local/bin/copy-text")) --take screenshots and convert to raw text
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(".local/bin/recorder")) --screenrecorder

--close notifications
hl.bind(mainMod .. " + COMMA", hl.dsp.exec_cmd("dunstctl close"))
hl.bind(mainMod .. " + SHIFT + COMMA", hl.dsp.exec_cmd("dunstctl close-all"))
hl.bind(mainMod .. " + ALT + COMMA", hl.dsp.exec_cmd("dunstctl history-pop"))

--toggle float with specific size and centered
hl.bind(mainMod .. " + T", function()
	hl.dispatch(hl.dsp.window.float({ action = "toggle" }))

	local win = hl.get_active_window()
	if win and win.floating then
		hl.dispatch(hl.dsp.window.resize({ x = 1000, y = 700, relative = false, window = "activewindow" }))
		hl.dispatch(hl.dsp.window.center())
	end
end)

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("~/.local/bin/window-pop"))
hl.bind(mainMod .. " + CTRL + F", hl.dsp.exec_cmd("~/.local/bin/tiled-fullscreen"))

--toggle window transparency
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.exec_cmd("~/.local/bin/transparency-toggle"))

-- for fullscreen apps with waybar visible
hl.bind(mainMod .. " + F", function()
	hl.dispatch(hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
end)
-- for absolute fullscreen
hl.bind(mainMod .. " + ALT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
	hl.bind(mainMod .. " + ALT + " .. key, hl.dsp.window.move({ workspace = tostring(i), follow = false }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + CTRL + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

--move windows inside one workspace move left, right, up, down
hl.bind(mainMod .. " + SHIFT + LEFT", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + RIGHT", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + UP", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + DOWN", hl.dsp.window.move({ direction = "down" }))

--resizing windows
local step = 50
hl.bind(mainMod .. " + CTRL + LEFT", hl.dsp.window.resize({ x = -step, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + RIGHT", hl.dsp.window.resize({ x = step, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + UP", hl.dsp.window.resize({ x = 0, y = -step, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + DOWN", hl.dsp.window.resize({ x = 0, y = step, relative = true }), { repeating = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume raise"), --wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ &&
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume lower"), --wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- &&
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), --wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle &&
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("swayosd-client --brightness +5 "), --brightnessctl -e4 -n2 set +10 &&
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("swayosd-client --brightness -5"), --brightnessctl -e4 -n2 set 10- &&
	{ locked = true, repeating = true }
)

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("swayosd-client --playerctl next"), { locked = true }) --playerctl next &&
hl.bind(
	"XF86AudioPause",
	hl.dsp.exec_cmd("swayosd-client --playerctl play-pause"), --playerctl play-pause &&
	{ locked = true }
)
hl.bind(
	"XF86AudioPlay",
	hl.dsp.exec_cmd("swayosd-client --playerctl play-pause"), --playerctl play-pause &&
	{ locked = true }
)
hl.bind(
	"XF86AudioPrev",
	hl.dsp.exec_cmd("swayosd-client --playerctl previous"), --playerctl previous &&
	{ locked = true }
)

hl.bind("XF86Presentation", hl.dsp.exec_cmd("~/.local/bin/powerprofiles"))

--to show about menu
hl.bind(mainMod .. " + KP_Enter ", hl.dsp.exec_cmd("~/.local/bin/about-system"))

--to hide/unhide waybar
hl.bind(mainMod .. " + CTRL + MINUS", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

-- Universal Copy (Fires Ctrl + Insert globally)
hl.bind("SUPER + C", hl.dsp.send_shortcut({ mods = "CTRL", key = "Insert" }))

-- Universal Paste (Fires Shift + Insert globally)
hl.bind("SUPER + V", hl.dsp.send_shortcut({ mods = "SHIFT", key = "Insert" }))

-- Universal Cut (Fires Ctrl + X globally)
hl.bind("SUPER + X", hl.dsp.send_shortcut({ mods = "CTRL", key = "X" }))

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

--Put require at the end if you want some portion in this doc\
--to be overwritten.
require("./extras/hyprland.lua")
