general {
    lock_cmd = pidof hyprlock || hyprlock
    # before_sleep_cmd = loginctl lock-session && hyprlock --grace 0
    # after_sleep_cmd = brightnessctl -r #hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
    # inhibit_sleep = 2
    ignore_dbus_inhibit = true
}

listener {
    timeout = 480
    on-timeout = notify-send "󰂚 HyprIdle Info" "You have been idle for a while. System will lock soon." -t 5000
    on-resume = dunstctl close
  }

# listener {
#     timeout = 560
#     on-timeout = brightnessctl -s set 0
#     on-resume = brightnessctl -r
# }

listener {
    timeout = 600
    on-timeout = loginctl lock-session && hyprlock
}

# listener {
#     timeout = 1200
#     on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
#     on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
# }

listener {
    timeout = 3600
    on-timeout = systemctl poweroff
}
